2025-03-03 10:50:09,409 INFO    MainThread:2718928 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-03 10:50:09,409 INFO    MainThread:2718928 [wandb_setup.py:_flush():67] Configure stats pid to 2718928
2025-03-03 10:50:09,409 INFO    MainThread:2718928 [wandb_setup.py:_flush():67] Loading settings from /home/mwahlin/.config/wandb/settings
2025-03-03 10:50:09,410 INFO    MainThread:2718928 [wandb_setup.py:_flush():67] Loading settings from /usr/terminus/data-xrm-01/stamplab/users/mwahlin/2025/trab_master/test_SR_CNN/wandb/settings
2025-03-03 10:50:09,410 INFO    MainThread:2718928 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-03 10:50:09,410 INFO    MainThread:2718928 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /usr/terminus/data-xrm-01/stamplab/users/mwahlin/2025/trab_master/test_SR_CNN/wandb/run-20250303_105009-yrpov6ix/logs/debug.log
2025-03-03 10:50:09,411 INFO    MainThread:2718928 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /usr/terminus/data-xrm-01/stamplab/users/mwahlin/2025/trab_master/test_SR_CNN/wandb/run-20250303_105009-yrpov6ix/logs/debug-internal.log
2025-03-03 10:50:09,411 INFO    MainThread:2718928 [wandb_init.py:init():761] calling init triggers
2025-03-03 10:50:09,411 INFO    MainThread:2718928 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.001, 'batch_size': 32, 'epochs': 10, 'optimizer': 'Adam', '_wandb': {}}
2025-03-03 10:50:09,411 INFO    MainThread:2718928 [wandb_init.py:init():784] starting backend
2025-03-03 10:50:09,412 INFO    MainThread:2718928 [wandb_init.py:init():788] sending inform_init request
2025-03-03 10:50:09,418 INFO    MainThread:2718928 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-03 10:50:09,418 INFO    MainThread:2718928 [wandb_init.py:init():803] backend started and connected
2025-03-03 10:50:09,419 INFO    MainThread:2718928 [wandb_init.py:init():896] updated telemetry
2025-03-03 10:50:09,428 INFO    MainThread:2718928 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-03 10:50:09,779 INFO    MainThread:2718928 [wandb_init.py:init():995] starting run threads in backend
2025-03-03 10:50:10,028 INFO    MainThread:2718928 [wandb_run.py:_console_start():2377] atexit reg
2025-03-03 10:50:10,029 INFO    MainThread:2718928 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-03 10:50:10,029 INFO    MainThread:2718928 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-03 10:50:10,029 INFO    MainThread:2718928 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-03 10:50:10,033 INFO    MainThread:2718928 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-03 10:50:10,072 WARNING MsgRouterThr:2718928 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/home/mwahlin/myterminus/mamba/envs/ML_env/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "/home/mwahlin/myterminus/mamba/envs/ML_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/home/mwahlin/myterminus/mamba/envs/ML_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mwahlin/myterminus/mamba/envs/ML_env/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
  File "/home/mwahlin/myterminus/mamba/envs/ML_env/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-03 10:50:10,075 INFO    MsgRouterThr:2718928 [mailbox.py:close():115] Closing mailbox, abandoning 2 handles.
