Traceback (most recent call last):
  File "/home/mwahlin/myterminus/2025/trab_master/test_SR_CNN/CNN_SR/ml_model_SR_CNN.py", line 254, in <module>
    train_loader, val_loader, test_loader = get_dataloaders(batch_size=BATCH_SIZE)
  File "/usr/terminus/data-xrm-01/stamplab/users/mwahlin/2025/trab_master/test_SR_CNN/CNN_SR/src/dataset.py", line 82, in get_dataloaders
    full_train_set = CIFAR10_SR(root=data_dir, train=True)
  File "/usr/terminus/data-xrm-01/stamplab/users/mwahlin/2025/trab_master/test_SR_CNN/CNN_SR/src/dataset.py", line 45, in __init__
    print(self.data)
AttributeError: 'CIFAR10_SR' object has no attribute 'data'
Traceback (most recent call last):
  File "/home/mwahlin/myterminus/2025/trab_master/test_SR_CNN/CNN_SR/ml_model_SR_CNN.py", line 254, in <module>
    train_loader, val_loader, test_loader = get_dataloaders(batch_size=BATCH_SIZE)
  File "/usr/terminus/data-xrm-01/stamplab/users/mwahlin/2025/trab_master/test_SR_CNN/CNN_SR/src/dataset.py", line 82, in get_dataloaders
    full_train_set = CIFAR10_SR(root=data_dir, train=True)
  File "/usr/terminus/data-xrm-01/stamplab/users/mwahlin/2025/trab_master/test_SR_CNN/CNN_SR/src/dataset.py", line 45, in __init__
    print(self.data)
AttributeError: 'CIFAR10_SR' object has no attribute 'data'
